export const SWDMV4_PERCENTILES = {
  FIFTH_PERCENTILE: 0.04, // A+
  TENTH_PERCENTILE: 0.079, // A
  TWENTIETH_PERCENTILE: 0.145, // B
  THIRTIETH_PERCENTILE: 0.209, // C
  FORTIETH_PERCENTILE: 0.278, // D
  FIFTIETH_PERCENTILE: 0.359, // E
};

export const SWDMV4_RATINGS = {
  FIFTH_PERCENTILE: 'A+',
  TENTH_PERCENTILE: 'A',
  TWENTIETH_PERCENTILE: 'B',
  THIRTIETH_PERCENTILE: 'C',
  FORTIETH_PERCENTILE: 'D',
  FIFTIETH_PERCENTILE: 'E',
};
